/**
 * The content contract.
 *
 * Every `.mdx` file in /content is parsed into a `Doc`. Adding a field here
 * means adding it to the validator in `schema.ts` — never one without the
 * other, or the build stops trusting the content.
 */

export type CollectionId = "decisions" | "blog" | "reports" | "guides";

export type Frontmatter = {
  title: string;
  description: string;
  /** Optional: defaults to the filename. Once published, never change it. */
  slug?: string;
  /** ISO date, YYYY-MM-DD. */
  date: string;
  /** ISO date. Defaults to `date`. */
  updated?: string;
  author?: string;
  category?: string;
  tags?: string[];
  /** Path under /public, or an absolute URL. Used for OpenGraph. */
  image?: string;
  /** Overrides the generated canonical. Use only for syndicated content. */
  canonical?: string;
  draft?: boolean;
  featured?: boolean;
  faq?: { question: string; answer: string }[];
  /** Slugs of related docs, in `collection/slug` or bare `slug` form. */
  related?: string[];
};

export type Heading = {
  /** Anchor id, generated by rehype-slug. */
  id: string;
  text: string;
  depth: 2 | 3;
};

export type Doc = {
  collection: CollectionId;
  slug: string;
  /** Site-relative URL, e.g. `/decision/business-valuation`. */
  href: string;
  frontmatter: Frontmatter;
  /** Raw MDX body, without frontmatter. */
  body: string;
  headings: Heading[];
  readingMinutes: number;
  wordCount: number;
};

/** A doc reduced to what listings need — cheap to pass around. */
export type DocSummary = Pick<
  Doc,
  "collection" | "slug" | "href" | "readingMinutes"
> & {
  title: string;
  description: string;
  date: string;
  updated: string;
  category?: string;
  tags: string[];
  featured: boolean;
};
