import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import { collectionList } from "@/lib/content/collections";
import { routes } from "@/lib/routes";
import { sellerIsPlaceholder } from "@/lib/site";

const read = (...parts: string[]) =>
  readFileSync(join(process.cwd(), ...parts), "utf8");

/** Every collection id is now also its route key. It was not always. */
function routeKey(id: string): string {
  return id;
}

describe("navigation reaches every collection", () => {
  // `routes.guides` pointed at `/blog` for as long as both existed, so the
  // header read "Guides" and went somewhere else. Nothing caught it, because
  // both were valid URLs and the page it landed on looked plausible.
  it("points each route at its own collection", () => {
    expect(routes.guides).toBe("/guides");
    expect(routes.faq).toBe("/faq");
    expect(routes.reports).toBe("/reports");
  });

  it("links every collection from the header, and builds the footer from the registry", () => {
    const header = read("components", "layout", "site-header.tsx");
    const missing = collectionList
      .map((collection) => collection.id)
      .filter((id) => !header.includes(`routes.${routeKey(id)}`));

    expect(missing, "collections with no header link").toEqual([]);
    expect(read("components", "layout", "site-footer.tsx")).toContain(
      "collectionList",
    );
  });

  // On-page anchors have to be root-absolute or they resolve against whatever
  // page the visitor is on: silently correct on the homepage, dead elsewhere.
  it("keeps homepage anchors root-absolute", () => {
    expect(routes.howItWorks.startsWith("/#")).toBe(true);
  });

  // The example is a generated page now, not a section of the homepage.
  it("points the example report at a page of its own", () => {
    expect(routes.exampleReport).toBe("/example-report");
  });
});

describe("both halves of the flow", () => {
  // This was a page of its own, linked from the header, which put the single
  // most persuasive thing on the site one click away from the thing it was
  // persuading you to buy. It is a block inside the report now.
  it("points at a report rather than a page of its own", () => {
    expect(routes.whatWeFind).toBe("/reports/what-is-hiding-in-my-figures");
    expect(routes.whatWeFind).not.toContain("#");
    expect(existsSync(join(process.cwd(), "app", "what-we-find"))).toBe(false);
  });

  it("is rendered by the report that describes it", () => {
    const report = read("content", "reports", "what-is-hiding-in-my-figures.mdx");
    expect(report).toContain("<WhatWeFind />");
    expect(read("components", "mdx", "index.tsx")).toContain("WhatWeFind");
  });

  it("is generated by the shipped engine, not written by hand", () => {
    expect(read("components", "mdx", "what-we-find.tsx")).toContain("demoTeaser");
  });
});

describe("the legal pages", () => {
  // A terms page naming a company that does not exist is worse than no terms
  // page: the first is a misrepresentation, the second is only a gap. So the
  // build goes red while the seller block is still placeholders.
  it("cannot go live with placeholder seller details", () => {
    expect(
      sellerIsPlaceholder,
      "fill in `seller` in lib/site.ts: legal name, KvK, VAT and a business email",
    ).toBe(false);
  });

  it("is linked from the footer, where people look for it", () => {
    const footer = read("components", "layout", "site-footer.tsx");
    expect(footer).toContain("/terms");
    expect(footer).toContain("/privacy");
  });
});

describe("the intake", () => {
  // Every call to action used to end on a browse list. A visitor who has
  // decided has to be able to act in one click, not two.
  it("is where the hero sends people", () => {
    expect(read("components", "sections", "hero.tsx")).toContain("routes.send");
  });

  it("is in the header, and is a page rather than a mailto", () => {
    expect(read("components", "layout", "site-header.tsx")).toContain("routes.send");
    expect(routes.send).toBe("/send");
  });

  it("names the business address, never a personal one", () => {
    const page = read("app", "send", "page.tsx");
    expect(page).toContain("seller.email");
    expect(page).not.toMatch(/@gmail\.com/);
  });

  it("has a page for the payment provider to return to", () => {
    expect(read("app", "thanks", "page.tsx")).toContain("on its way");
  });
});

describe("a redirected page is a deleted page", () => {
  /**
   * The site was written in two languages and then one was chosen. The Dutch
   * pages were removed from the working copy and never from the repository, so
   * they went on being built, served and listed in the sitemap: five pages,
   * four of them near-duplicates of an English page, on one domain, with
   * nothing telling a search engine which was which. Nobody noticed for a week.
   *
   * A redirect alone would not have caught it either. The redirect fires for a
   * visitor and the sitemap still advertises the old URL, so the duplicate
   * stays discoverable. The only fix that works is removing the file, and this
   * is the test that says so.
   */
  const config = readFileSync(join(process.cwd(), "next.config.ts"), "utf8");
  const sources = [...config.matchAll(/source:\s*"([^"]+)"/g)].map((m) => m[1]);

  const collectionOf: Record<string, string> = {
    "/reports": "reports",
    "/guides": "guides",
    "/faq": "faq",
  };

  it("has redirects at all, or this test is asserting nothing", () => {
    expect(sources.length).toBeGreaterThan(0);
  });

  it("does not still ship the pages it redirects away from", () => {
    const survivors = sources
      .filter((source) => !source.includes(":"))
      .map((source) => {
        const at = source.lastIndexOf("/");
        const dir = collectionOf[source.slice(0, at)];
        return dir ? join(process.cwd(), "content", dir, `${source.slice(at + 1)}.mdx`) : "";
      })
      .filter((path) => path !== "" && existsSync(path));

    expect(
      survivors,
      "these files are still built and still in the sitemap despite being redirected away from",
    ).toEqual([]);
  });
});
